### ISSUE TITLE
vmware.vmware_rest.vm_moid lookup does not return moid  from vm in subfolder

### ISSUE THREAD

**Issue by ewilson57** [ansible-collections/vmware_rest#418]
##### SUMMARY
vmware.vmware_rest.vm_moid does not return MOID of a vm that is in a subfolder. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware_rest/vm_moid_lookup

##### ANSIBLE VERSION
```paste below
ansible [core 2.14.5]
  config file = None
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/opt/venv/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible/opt/venv/ansible/bin/ansible
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/home/ansible/opt/venv/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```
##### COLLECTION VERSION
```paste below
Collection         Version
------------------ -------
vmware.vmware_rest 2.3.1  
```
##### CONFIGURATION
```paste below
CONFIG_FILE() = None
```
##### OS / ENVIRONMENT
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"

##### STEPS TO REPRODUCE
```yaml
---
- name: Lookup MoIDs of objects
  hosts: localhost
  gather_facts: false
  vars:
    vm_name: web01
  tasks:
    - name: Lookup MoID of the vm
      ansible.builtin.debug:
        msg: "{{ lookup('vmware.vmware_rest.vm_moid', vm_name) }}"
```
##### EXPECTED RESULTS
```paste below
ok: [localhost] => {
    "msg": "vm-664"
}
```

##### ACTUAL RESULTS
```paste below
ok: [localhost] => {
    "msg": ""
```
