### ISSUE TITLE
vmware_rest modules don't work when it not install cloud.common

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/vmware_rest#42]
##### SUMMARY

I tried vmware_rest module the following error occurs when not install cloud.common collection.

```
fatal: [localhost]: FAILED! => {"msg": "error processing module_util ansible_collections.cloud.common.plugins.module_utils.turbo.module.AnsibleTurboModule loading redirected collection cloud.common: unable to locate collection cloud.common"}
```

I'm looking like the vmware_rest modules to work even if the cloud.common not installed.  
For example, the following code is vcenter_datacenter_info a part.

```python
(snip)
try:
    from ansible_collections.cloud.common.plugins.module_utils.turbo.module import (
        AnsibleTurboModule as AnsibleModule,
    )
except ImportError:
    from ansible.module_utils.basic import AnsibleModule
(snip)
```

Is cloud.common required for the vmware_rest modules to work?
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

plugins/modules/vcenter_datacenter_info

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.10.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/vmware_rest/venv/lib64/python3.6/site-packages/ansible
  executable location = /root/vmware_rest/venv/bin/ansible
  python version = 3.6.8 (default, Aug  7 2019, 17:28:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```
# ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

```
# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```

##### STEPS TO REPRODUCE

I executed the following playbook.

```yaml
---
- name: Test Playbook
  hosts: localhost
  gather_facts: no
  collections:
    - vmware.vmware_rest
  tasks:
    - name: Gather info for datacenter
      vcenter_datacenter_info:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_certs: false
```

##### EXPECTED RESULTS

Even if not install cloud.common the vmware_rest is to work.

##### ACTUAL RESULTS

The cloud.common error occurs
